project_id = "btfecoijribbvynljxxy"

[functions.search-medicamento]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-maintenance]
verify_jwt = false

[functions.whatsapp-bootstrap]
verify_jwt = false
